/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XprinterRouteImport } from './routes/xprinter'
import { Route as IndexRouteImport } from './routes/index'

const XprinterRoute = XprinterRouteImport.update({
  id: '/xprinter',
  path: '/xprinter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/xprinter': typeof XprinterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/xprinter': typeof XprinterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/xprinter': typeof XprinterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/xprinter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/xprinter'
  id: '__root__' | '/' | '/xprinter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  XprinterRoute: typeof XprinterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xprinter': {
      id: '/xprinter'
      path: '/xprinter'
      fullPath: '/xprinter'
      preLoaderRoute: typeof XprinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  XprinterRoute: XprinterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
